app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::group(['namespace' => 'Api'], function() {
    // List all Classes
    Route::resource('classes','ClassController');
    // Get all the Grades with Classes
    Route::get('grades','GradeController@index');
    // Routes for Student
    Route::resource('students','StudentController');

});


Route::group(['namespace' => 'Web'], function() {
    // Routes for Class
    Route::resource('class','ClassController');
    // Routes for Grade
    Route::resource('grade','GradeController');
    // Routes for Student
    Route::resource('student','StudentController');

});


Route::auth();

Route::get('/home', 'HomeController@index');

app/Http/Controllers/Api/ClassController.php
<?php

namespace pyxle\Http\Controllers\Api;

use Illuminate\Http\Request;

use pyxle\Http\Requests;
use pyxle\Http\Controllers\Controller;
use pyxle\SchoolClass;

class ClassController extends Controller
{
    protected $schoolClass;

    public function __construct(SchoolClass $schoolClass)
    {
        $this->schoolClass = $schoolClass;
    }

    public function index()
    {
        $classes = $this->schoolClass->all();
        return $classes;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified class from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $class = SchoolClass::find($id);
        $class->delete();
        return response()->json('Successfully deleted');
    }
}

app/Http/Controllers/Web/ClassController.php
<?php

namespace pyxle\Http\Controllers\Web;

use pyxle\Grade;
use Illuminate\Http\Request;

use pyxle\Http\Requests;
use pyxle\Http\Controllers\Controller;
use pyxle\SchoolClass;
use pyxle\Http\Requests\ClassRequest;
use Illuminate\Support\Facades\Redirect;

class ClassController extends Controller
{
    protected $schoolClass;
    protected $grade;

    public function __construct(SchoolClass $schoolClass,Grade $grade)
    {
        $this->schoolClass = $schoolClass;
        $this->grade = $grade;
    }
    /**
     * Display a listing of the Classes with related Grades.
     */
    public function index()
    {
        // All the Grades with related Classes.
        $classes = Grade::with('classes')->get();
        return view('class/index',compact('classes'));
    }

    /**
     * Show the form for creating a new Class.
     */
    public function create()
    {
        // Get all the grades
        $grades = Grade::lists('grade','id');

        // Add new class
        return view('class/create',compact('grades'));
    }

    /**
     * Store a newly created Class in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ClassRequest $request)
    {
        $class = $this->schoolClass;

        $class->class = $request->class;
        $class->grade_id = $request->grade;

        $class->save();
        return Redirect::route('class.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/class/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading">Grades
                        <p class="pull-right"> <a href="{!! route('class.index') !!}" class="btn btn-success" /> Classes </a> </p></div>

                    <div class="panel-body">
                        {!! Form::open(array('route'=>'class.store')) !!}
                        <div class="row">
                            <div class="col-md-6">
                                <fieldset class="form-group {!! ($errors->has('grade')) ? 'has-error' : '' !!}">
                                    {!! Form::label('grade', 'Grade') !!}
                                    {!! Form::select('grade',  $grades,null, ['class' => 'form-control']) !!}
                                    <span class="help-block">{!! $errors->has('grade')? $errors->first('grade'):'' !!}</span>
                                </fieldset>
                            </div>
                            <div class="col-md-6">
                                <md-input-container class="form-group {!! ($errors->has('class')) ? 'has-error' : '' !!}">
                                    {!! Form::label('class', 'Class') !!}
                                    {!! Form::text('class', null, ['class' => 'form-control']) !!}
                                    <span class="help-block">{!! $errors->has('class')? $errors->first('class'):'' !!}</span>
                                </md-input-container>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                {!! Form::submit('Save',array('class'=>'btn btn-success')) !!}
                                {!! link_to_route('class.index','Cancel',[],['class' => 'btn btn-danger']) !!}
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/class/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading">Classes
                        <p class="pull-right"> <a href="{!! route('class.create') !!}" class="btn btn-success" /> Add </a> </p>
                    </div>

                    <div class="panel-body">
                        <table class="table table-bordered">
                            <tr>
                                <th>Grades</th>
                                <th>Classes</th>
                            </tr>

                            @foreach($classes as $class)
                                 <tr>
                                    <td><b>{{$class->grade}}</b></td>
                                 </tr>
                                @foreach($class->classes as $c)
                                    <tr> <td></td>
                                        <td>{{$c->class}}</td>
                                    </tr>
                                @endforeach
                            @endforeach
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection