app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::group(['namespace' => 'Api'], function() {
    // List all Classes
    Route::resource('classes','ClassController');
    // Get all the Grades with Classes
    Route::get('grades','GradeController@index');
    // Routes for Student
    Route::resource('students','StudentController');

});


Route::group(['namespace' => 'Web'], function() {
    // Routes for Class
    Route::resource('class','ClassController');
    // Routes for Grade
    Route::resource('grade','GradeController');
    // Routes for Student
    Route::resource('student','StudentController');

});


Route::auth();

Route::get('/home', 'HomeController@index');

app/Student.php
<?php

namespace pyxle;

use Illuminate\Database\Eloquent\Model;
use pyxle\Grade;
use pyxle\SchoolClass;

class Student extends Model
{
    // Student belongs to a Grade
    public function grade(){
        return $this->belongsTo(Grade::class);
    }

    // Student Belongs to a Class
    public function classes()
    {
        return $this->belongsTo(SchoolClass::class);
    }
}

app/Http/Controllers/Api/StudentController.php
<?php

namespace pyxle\Http\Controllers\Api;

use Illuminate\Http\Request;

use pyxle\Http\Requests;
use pyxle\Http\Controllers\Controller;
use pyxle\Student;
use pyxle\Grade;
use pyxle\Http\Requests\StudentAPIRequest;

class StudentController extends Controller
{
    protected $student;

    public function __construct(Student $student)
    {
        $this->student = $student;
    }
    /**
     * Display a listing of the students.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $students = Grade::with('students')->get();
        return response()->json($students);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StudentAPIRequest $request)
    {
        $student = $this->student;
        $student->name = $request->name;
        $student->gender = $request->gender;
        $student->age = $request->age;
        $student->dateOfBirth = $request->dob;
        $student->address = $request->address;
        $student->phone = $request->phone;
        $student->grade_id = $request->grade;
        $student->class_id = $request->class;

        $student->save();

        return response()->json($student);
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Web/StudentController.php
<?php

namespace pyxle\Http\Controllers\Web;

use pyxle\SchoolClass;
use Illuminate\Http\Request;

use pyxle\Http\Requests;
use pyxle\Http\Controllers\Controller;
use pyxle\Student;
use pyxle\Grade;
use Illuminate\Support\Facades\DB;
use pyxle\Http\Requests\StudentRequest;
use Illuminate\Support\Facades\Redirect;

class StudentController extends Controller
{
    protected $student;

    public function __construct(Student $student)
    {
        $this->student = $student;
    }
    /**
     * Display a listing of the Students.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Return all the students details
        $students = Grade::with('students')->get();
        return view('student/index',compact('students'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // Get all the grades
        $grades = Grade::lists('grade','id');
        // Get all the classes
        $classes = SchoolClass::lists('class','id');
        return view('student/create',compact('grades','classes'));
    }

    /**
     * Store a newly created Student in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StudentRequest $request)
    {
        $student = $this->student;
        $student->name = $request->name;
        $student->gender = $request->gender;
        $student->age = $request->age;
        $student->dateOfBirth = $request->dob;
        $student->address = $request->address;
        $student->phone = $request->phone;
        $student->grade_id = $request->grade;
        $student->class_id = $request->class;

        $student->save();

        return Redirect::route('student.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/student/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading">Grades
                        <p class="pull-right"> <a href="{!! route('student.index') !!}" class="btn btn-success" /> Students </a> </p></div>

                    <div class="panel-body">
                        {!! Form::open(array('route'=>'student.store')) !!}
                        <div class="row">
                            <div class="col-md-6">
                                <fieldset class="form-group {!! ($errors->has('grade')) ? 'has-error' : '' !!}">
                                    {!! Form::label('grade', 'Grade') !!}
                                    {!! Form::select('grade',  $grades,null, ['class' => 'form-control']) !!}
                                    <span class="help-block">{!! $errors->has('grade')? $errors->first('grade'):'' !!}</span>
                                </fieldset>
                            </div>
                            <div class="col-md-6">
                                <md-input-container class="form-group {!! ($errors->has('class')) ? 'has-error' : '' !!}">
                                    {!! Form::label('class', 'Class') !!}
                                    {!! Form::select('class',$classes, null, ['class' => 'form-control']) !!}
                                    <span class="help-block">{!! $errors->has('class')? $errors->first('class'):'' !!}</span>
                                </md-input-container>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <md-input-container class="form-group {!! ($errors->has('name')) ? 'has-error' : '' !!}">
                                    {!! Form::label('name', 'Name') !!}
                                    {!! Form::text('name', null, ['class' => 'form-control']) !!}
                                    <span class="help-block">{!! $errors->has('name')? $errors->first('name'):'' !!}</span>
                                </md-input-container>
                            </div>
                            <div class="col-md-6">
                                <fieldset class="form-group {!! ($errors->has('gender')) ? 'has-error' : '' !!}">
                                    {!! Form::label('gender', 'Gender') !!}
                                    {!! Form::select('gender',  array('male'=>'Male','female'=>'Female'),null, ['class' => 'form-control']) !!}
                                    <span class="help-block">{!! $errors->has('grade')? $errors->first('grade'):'' !!}</span>
                                </fieldset>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <md-input-container class="form-group {!! ($errors->has('age')) ? 'has-error' : '' !!}">
                                    {!! Form::label('age', 'Age') !!}
                                    {!! Form::text('age', null, ['class' => 'form-control']) !!}
                                    <span class="help-block">{!! $errors->has('age')? $errors->first('age'):'' !!}</span>
                                </md-input-container>
                            </div>
                            <div class="col-md-6">
                                <fieldset class="form-group {!! ($errors->has('dob')) ? 'has-error' : '' !!}">
                                    {!! Form::label('dob', 'Date of birth') !!}
                                    {!! Form::date('dob', null, ['class' => 'form-control']) !!}
                                    <span class="help-block">{!! $errors->has('dob')? $errors->first('dob'):'' !!}</span>
                                </fieldset>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <md-input-container class="form-group {!! ($errors->has('address')) ? 'has-error' : '' !!}">
                                    {!! Form::label('address', 'Address') !!}
                                    {!! Form::text('address', null, ['class' => 'form-control']) !!}
                                    <span class="help-block">{!! $errors->has('address')? $errors->first('address'):'' !!}</span>
                                </md-input-container>
                            </div>
                            <div class="col-md-6">
                                <fieldset class="form-group {!! ($errors->has('phone')) ? 'has-error' : '' !!}">
                                    {!! Form::label('phone', 'Phone') !!}
                                    {!! Form::text('phone', null, ['class' => 'form-control']) !!}
                                    <span class="help-block">{!! $errors->has('phone')? $errors->first('phone'):'' !!}</span>
                                </fieldset>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                {!! Form::submit('Save',array('class'=>'btn btn-success')) !!}
                                {!! link_to_route('student.index','Cancel',[],['class' => 'btn btn-danger']) !!}
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/student/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading">Students
                        <p class="pull-right"> <a href="{!! route('student.create') !!}" class="btn btn-success" /> Add </a> </p>
                    </div>

                    <div class="panel-body">
                        <table class="table table-bordered">
                            <tr>
                                <th>Grade</th>
                                <th>Name</th>
                                <th>Gender</th>
                                <th>Age</th>
                                <th>Date of birth</th>
                                <th>Address</th>
                                <th>Phone</th>
                            </tr>

                            @foreach($students as $grade)
                                {{--If Grade has Students only Display Grades--}}
                                @if(count($grade->students)>0)
                                    <tr>
                                        <td><b>{{$grade->grade}}</b></td>
                                    </tr>
                                @endif
                            @foreach($grade->students as $student)
                                <tr>
                                    <td></td>
                                    <td>{{$student->name}}</td>
                                    <td>{{$student->gender}}</td>
                                    <td>{{$student->age}}</td>
                                    <td>{{$student->dateOfBirth}}</td>
                                    <td>{{$student->address}}</td>
                                    <td>{{$student->phone}}</td>
                                </tr>
                            @endforeach
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection