app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::group(['namespace' => 'Api'], function() {
    // List all Classes
    Route::resource('classes','ClassController');
    // Get all the Grades with Classes
    Route::get('grades','GradeController@index');
    // Routes for Student
    Route::resource('students','StudentController');

});


Route::group(['namespace' => 'Web'], function() {
    // Routes for Class
    Route::resource('class','ClassController');
    // Routes for Grade
    Route::resource('grade','GradeController');
    // Routes for Student
    Route::resource('student','StudentController');

});


Route::auth();

Route::get('/home', 'HomeController@index');

app/Grade.php
<?php

namespace pyxle;

use Illuminate\Database\Eloquent\Model;
use pyxle\SchoolClass;

class Grade extends Model
{
    protected $table = 'grades';

    // Grade and Classes has One to Many relationship
    public function classes()
    {
        return $this->hasMany(SchoolClass::class);
    }

    // Grade and Students has One to Many relationship
    public function students()
    {
        return $this->hasMany(Student::class);
    }
}

app/Http/Controllers/Api/GradeController.php
<?php

namespace pyxle\Http\Controllers\API;

use pyxle\Grade;
use Illuminate\Http\Request;

use pyxle\Http\Requests;
use pyxle\Http\Controllers\Controller;
use GradeTransformer;
use League\Fractal\Manager;
use League\Fractal\Resource\Collection;

class GradeController extends Controller
{
    protected $grade;
    protected $manager;

    public function __construct(Grade $grade,Manager $manager){
        $this->grade = $grade;
        $this->manager = $manager;
    }

    /*
   * List all the Grades
   */
    public function index(){
        $grades = Grade::with('classes')->get();
        // Apply Transformer for Collection of data.
//        $resource = new Collection($grades,new GradeTransformer());
//        $grades = $this->manager->createData($resource)->toArray();
        return response()->json($grades);
    }
}

app/Http/Controllers/Web/GradeController.php
<?php

namespace pyxle\Http\Controllers\Web;

use Illuminate\Http\Request;

use pyxle\Http\Requests;
use pyxle\Http\Controllers\Controller;
use pyxle\Grade;
use pyxle\Http\Requests\GradeRequest;
use Illuminate\Support\Facades\Redirect;

class GradeController extends Controller
{
    protected $grade;

    public function __construct(Grade $grade)
    {
        $this->grade = $grade;
    }
    /**
     * Display listing of all the Grades
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $grades = $this->grade->all();
        return view('grade/index',compact('grades'));
    }

    /**
     * Add a new Grade
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('grade/create');
    }

    /**
     * Store a newly created Grade in storage.
     */
    public function store(GradeRequest $request)
    {
        $grade = $this->grade;
        $grade->grade = $request->grade;
        $grade->save();

        // Redirect to Grade index page
        return Redirect::route('grade.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/grade/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading">Grades
                        <p class="pull-right"> <a href="{!! route('grade.index') !!}" class="btn btn-success" /> Grades </a> </p></div>

                    <div class="panel-body">
                        {!! Form::open(array('route'=>'grade.store')) !!}
                        <div class="row">
                            <div class="col-md-6">
                                <md-input-container class="form-group {!! ($errors->has('grade')) ? 'has-error' : '' !!}">
                                    {!! Form::label('grade', 'Grade') !!}
                                    {!! Form::number('grade', null, ['class' => 'form-control']) !!}
                                    <span class="help-block">{!! $errors->has('grade')? $errors->first('grade'):'' !!}</span>
                                </md-input-container>
                            </div>

                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                {!! Form::submit('Save',array('class'=>'btn btn-success')) !!}
                                {!! link_to_route('grade.index','Cancel',[],['class' => 'btn btn-danger']) !!}
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/grade/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading">Grades
                    <p class="pull-right"> <a href="{!! route('grade.create') !!}" class="btn btn-success" /> Add </a> </p></div>

                    <div class="panel-body">
                        <table class="table table-responsive">
                            <tr>
                                <th>Grades</th>
                            </tr>
                            @foreach($grades as $grade)
                                <tr>
                                    <td>
                                        {{$grade->grade}}
                                    </td>
                                </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection